(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-page/qui-page"],{"5cc7":function(e,n,t){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var r=t("2f62");o(t("13a0"));function o(e){return e&&e.__esModule?e:{default:e}}function u(e,n){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);n&&(r=r.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),t.push.apply(t,r)}return t}function i(e){for(var n=1;n<arguments.length;n++){var t=null!=arguments[n]?arguments[n]:{};n%2?u(Object(t),!0).forEach((function(n){a(e,n,t[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):u(Object(t)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}))}return e}function a(e,n,t){return n in e?Object.defineProperty(e,n,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[n]=t,e}var c={props:{header:{type:Boolean,default:!0}},data:function(){return{isRun:!1}},computed:i(i({},(0,r.mapState)({forumError:function(e){return e.forum.error}})),{},{loading:function(){return this.forumError.loading},showMessage:function(){return-1!==["not_install","site_closed","ban_user","model_not_found","dataerro","permission_denied"].indexOf(this.forumError.code)}}),watch:{forumError:function(e){!1!==e.loading||e.code||this.$emit("pageLoaded")}},mounted:function(){this.$store.dispatch("session/setAuth",this.$refs.auth)},methods:{open:function(){this.loading||this.showMessage||this.$store.getters["session/get"]("isLogin")||this.$refs.auth.open()},close:function(){this.$refs.auth.close()},login:function(){this.$refs.auth.close()}}};n.default=c},"716f":function(e,n,t){"use strict";t.r(n);var r=t("e5b0"),o=t("a66a");for(var u in o)"default"!==u&&function(e){t.d(n,e,(function(){return o[e]}))}(u);t("be7d");var i,a=t("f0c5"),c=Object(a["a"])(o["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],i);n["default"]=c.exports},"84de":function(e,n,t){},a66a:function(e,n,t){"use strict";t.r(n);var r=t("5cc7"),o=t.n(r);for(var u in r)"default"!==u&&function(e){t.d(n,e,(function(){return r[e]}))}(u);n["default"]=o.a},be7d:function(e,n,t){"use strict";var r=t("84de"),o=t.n(r);o.a},e5b0:function(e,n,t){"use strict";t.d(n,"b",(function(){return o})),t.d(n,"c",(function(){return u})),t.d(n,"a",(function(){return r}));var r={uLoading:function(){return t.e("components/u-loading/u-loading").then(t.bind(null,"cbac"))},quiPageMessage:function(){return Promise.all([t.e("common/vendor"),t.e("components/qui-page-message/qui-page-message")]).then(t.bind(null,"3eb1"))},uniPopup:function(){return t.e("components/uni-popup/uni-popup").then(t.bind(null,"a5b1"))},quiAuth:function(){return Promise.all([t.e("common/vendor"),t.e("components/qui-auth/qui-auth")]).then(t.bind(null,"7a31"))}},o=function(){var e=this,n=e.$createElement;e._self._c},u=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-page/qui-page-create-component',
    {
        'components/qui-page/qui-page-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("716f"))
        })
    },
    [['components/qui-page/qui-page-create-component']]
]);
