(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-audio/qui-audio"],{"2fb86":function(t,i,n){},"8a4b":function(t,i,n){"use strict";(function(t){Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var n={props:{src:{type:String,default:""},audioId:{type:String,default:""},autoplay:{type:Boolean,default:!1},name:{type:String,default:""},canPlay:{type:Boolean,default:!0},color:{type:String,default:"#1878f3"}},data:function(){return{audio:null,currentTime:"00 : 00",duration:"00 : 00",durationTime:0,current:"",loading:!1,paused:!0,seek:!1}},watch:{current:function(t){t&&(this.currentTime=this.format(t))}},mounted:function(){},destroyed:function(){this.audio&&this.audio.destroy()},methods:{initAudio:function(){var i=this;this.audio=t.createInnerAudioContext(),this.audio.src=this.src,this.loading=!0,this.audio.onTimeUpdate((function(){i.durationTime||i.setDuration(),i.seek||(i.current=i.audio.currentTime)})),this.audio.onPlay((function(){i.paused=!1})),this.audio.onPause((function(){i.paused=!0})),this.audio.onEnded((function(){i.paused=!0,i.current=0,i.currentTime="00 : 00"})),this.audio.onSeeked((function(){i.seek=!1}))},operation:function(){this.canPlay&&(this.audio||this.initAudio(),this.paused?(this.audio.play(),this.$emit("audioPlay",this.audioId)):this.audio.pause())},audioPause:function(){this.paused&&!this.loading||this.audio.pause()},format:function(t){if(t)return"".concat("0".repeat(2-String(Math.floor(t/60)).length)+Math.floor(t/60),":").concat("0".repeat(2-String(Math.floor(t%60)).length)).concat(Math.floor(t%60))},change:function(t){this.audio.seek(t.detail.value)},setDuration:function(){this.duration=this.format(this.audio.duration),this.durationTime=this.audio.duration,this.loading=!1},fileClick:function(){this.$emit("fileClick")}}};i.default=n}).call(this,n("543d")["default"])},"969b":function(t,i,n){"use strict";n.r(i);var u=n("d77d"),e=n("c76b");for(var o in e)"default"!==o&&function(t){n.d(i,t,(function(){return e[t]}))}(o);n("b8c4");var a,r=n("f0c5"),d=Object(r["a"])(e["default"],u["b"],u["c"],!1,null,"d0b1c150",null,!1,u["a"],a);i["default"]=d.exports},b8c4:function(t,i,n){"use strict";var u=n("2fb86"),e=n.n(u);e.a},c76b:function(t,i,n){"use strict";n.r(i);var u=n("8a4b"),e=n.n(u);for(var o in u)"default"!==o&&function(t){n.d(i,t,(function(){return u[t]}))}(o);i["default"]=e.a},d77d:function(t,i,n){"use strict";n.d(i,"b",(function(){return e})),n.d(i,"c",(function(){return o})),n.d(i,"a",(function(){return u}));var u={quiIcon:function(){return n.e("components/qui-icon/qui-icon").then(n.bind(null,"708e"))}},e=function(){var t=this,i=t.$createElement;t._self._c;t._isMounted||(t.e0=function(i){t.seek=!0,t.current=i.detail.value})},o=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-audio/qui-audio-create-component',
    {
        'components/qui-audio/qui-audio-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("969b"))
        })
    },
    [['components/qui-audio/qui-audio-create-component']]
]);
