(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-share/qui-share"],{"16a0":function(t,e,n){"use strict";n.d(e,"b",(function(){return i})),n.d(e,"c",(function(){return a})),n.d(e,"a",(function(){return o}));var o={quiIcon:function(){return n.e("components/qui-icon/qui-icon").then(n.bind(null,"708e"))}},i=function(){var t=this,e=t.$createElement,n=(t._self._c,t.i18n.t("home.cancel"));t.$mp.data=Object.assign({},{$root:{g0:n}})},a=[]},"1ee9":function(t,e,n){"use strict";n.r(e);var o=n("16a0"),i=n("776f");for(var a in i)"default"!==a&&function(t){n.d(e,t,(function(){return i[t]}))}(a);n("60bb");var r,s=n("f0c5"),u=Object(s["a"])(i["default"],o["b"],o["c"],!1,null,null,null,!1,o["a"],r);e["default"]=u.exports},"2d44":function(t,e,n){},"60bb":function(t,e,n){"use strict";var o=n("2d44"),i=n.n(o);i.a},"776f":function(t,e,n){"use strict";n.r(e);var o=n("c43a"),i=n.n(o);for(var a in o)"default"!==a&&function(t){n.d(e,t,(function(){return o[t]}))}(a);e["default"]=i.a},c43a:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o=a(n("04de")),i=a(n("13a0"));function a(t){return t&&t.__esModule?t:{default:t}}var r={mixins:[o.default,i.default],props:{shareType:{type:String,default:"top"},nowThreadId:{type:String,default:""}},data:function(){return{bottomData:[{text:this.i18n.t("home.generatePoster"),icon:"icon-poster",name:"wx"},{text:this.i18n.t("home.wxShare"),icon:"icon-wx-friends",name:"wx"}]}},mounted:function(){this.forums.set_site&&"pay"===this.forums.set_site.site_mode&&(this.bottomData=[{text:this.i18n.t("home.generatePoster"),icon:"icon-poster",name:"wx"}])},methods:{cancel:function(){this.$emit("close")},shareContent:function(e){var n=this.shareType;this.$store.getters["session/get"]("isLogin")||(t.setStorage({key:"page",data:"/pages/home/index"}),this.mpLoginMode()),"top"===n?0===e&&t.navigateTo({url:"/pages/share/site"}):0===e&&t.navigateTo({url:"/pages/share/topic?id=".concat(this.nowThreadId)})}}};e.default=r}).call(this,n("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-share/qui-share-create-component',
    {
        'components/qui-share/qui-share-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("1ee9"))
        })
    },
    [['components/qui-share/qui-share-create-component']]
]);
