(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-avatar/qui-avatar"],{"0c83":function(t,e,n){},"78df":function(t,e,n){"use strict";n.r(e);var r=n("9745"),a=n.n(r);for(var u in r)"default"!==u&&function(t){n.d(e,t,(function(){return r[t]}))}(u);e["default"]=a.a},9745:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=a(n("bde2"));function a(t){return t&&t.__esModule?t:{default:t}}var u={80:"font-size: 24px;line-height: 80rpx;",70:"font-size: 22px;line-height: 70rpx;",60:"font-size: 20px;line-height: 60rpx;",50:"font-size: 18px;line-height: 50rpx;"},i={props:{user:{type:[Object,String],default:function(){return{}}},size:{type:[Number,String],default:80},isReal:{type:Boolean,default:!1}},data:function(){return{styleText:""}},computed:{avatarUrl:function(){return this.user.avatarUrl&&0!==this.user.avatarUrl.indexOf("/static/noavatar.gif")},usernameAt:function(){return this.user.username?this.user.username.charAt(0).toUpperCase():this.i18n.t("core.noavatar")}},mounted:function(){this.styleText=this.style()},methods:{style:function(){var t=(0,r.default)(this.usernameAt);return"background-color: #".concat(t,";").concat(u[this.size])},error:function(){this.user.avatarUrl=!1},click:function(){this.$emit("click")}}};e.default=i},b6d9:function(t,e,n){"use strict";n.r(e);var r=n("d3a7"),a=n("78df");for(var u in a)"default"!==u&&function(t){n.d(e,t,(function(){return a[t]}))}(u);n("f48f");var i,c=n("f0c5"),o=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"64f556c7",null,!1,r["a"],i);e["default"]=o.exports},d3a7:function(t,e,n){"use strict";var r;n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return u})),n.d(e,"a",(function(){return r}));var a=function(){var t=this,e=t.$createElement;t._self._c},u=[]},f48f:function(t,e,n){"use strict";var r=n("0c83"),a=n.n(r);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-avatar/qui-avatar-create-component',
    {
        'components/qui-avatar/qui-avatar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b6d9"))
        })
    },
    [['components/qui-avatar/qui-avatar-create-component']]
]);
