(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/qui-header/qui-header"],{"1aef":function(e,t,n){},"796e":function(e,t,n){"use strict";var u=n("1aef"),o=n.n(u);o.a},"897d":function(e,t,n){"use strict";n.r(t);var u=n("f6de"),o=n.n(u);for(var i in u)"default"!==i&&function(e){n.d(t,e,(function(){return u[e]}))}(i);t["default"]=o.a},"9b58":function(e,t,n){"use strict";n.r(t);var u=n("d875"),o=n("897d");for(var i in o)"default"!==i&&function(e){n.d(t,e,(function(){return o[e]}))}(i);n("796e");var r,a=n("f0c5"),f=Object(a["a"])(o["default"],u["b"],u["c"],!1,null,null,null,!1,u["a"],r);t["default"]=f.exports},d875:function(e,t,n){"use strict";n.d(t,"b",(function(){return o})),n.d(t,"c",(function(){return i})),n.d(t,"a",(function(){return u}));var u={quiIcon:function(){return n.e("components/qui-icon/qui-icon").then(n.bind(null,"708e"))}},o=function(){var e=this,t=e.$createElement;e._self._c},i=[]},f6de:function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var u="header-h5";u="";var o={name:"QuiHeader",props:{headImg:{type:String,default:""},backgroundHeadFullImg:{type:String,default:""},themeNum:{type:[Number,String],default:0},homecontent:{type:String,default:""},iconcolor:{type:String,default:"#fff"},postNum:{type:[Number,String],default:0},share:{type:String,default:""},shareBtn:{type:String,default:""},shareShow:{type:Boolean,default:!1},title:{type:String,default:""},isShowBack:{type:Boolean,default:!0},isShowHome:{type:Boolean,default:!0},isShowMore:{type:Boolean,default:!0},color:{type:String,default:""}},data:function(){return{headerH5:u}},computed:{t:function(){return this.i18n.t("home")}},onLond:function(){},methods:{open:function(e){this.$emit("click",e)},closeShare:function(e){this.$emit("closeShare",e)},logoClick:function(e){this.$emit("logoClick",e)}}};t.default=o}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/qui-header/qui-header-create-component',
    {
        'components/qui-header/qui-header-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("9b58"))
        })
    },
    [['components/qui-header/qui-header-create-component']]
]);
